### ISSUE TITLE
Your message to amazon-pay-delivery-notification@amazon.com couldn't be delivered.

### ISSUE THREAD

**Issue by JohnHe404** [amzn/amazon-pay-api-sdk-dotnet#1]
Original Message   Details
--
Created Date:               10/8/2019 11:45:35 PM                       Sender Address:               admin@killsb.com                       Recipient Address:               amazon-pay-delivery-notification@amazon.com                       Subject:               amazon pay sdk v2 Public and     Private Keys | Created Date: | 10/8/2019 11:45:35 PM | Sender Address: | admin@killsb.com | Recipient Address: | amazon-pay-delivery-notification@amazon.com | Subject: | amazon pay sdk v2 Public and     Private Keys
Created Date: | 10/8/2019 11:45:35 PM
Sender Address: | admin@killsb.com
Recipient Address: | amazon-pay-delivery-notification@amazon.com
Subject: | amazon pay sdk v2 Public and     Private Keys
Error Details
Reported error:               550 5.0.350 Remote server     returned an error -> 550 #5.1.0 Address rejected.                        DSN generated by:               HK2PR04MB3889.apcprd04.prod.outlook.com                       Remote server:               stmp-fw-0102.amazon.com | Reported error: | 550 5.0.350 Remote server     returned an error -> 550 #5.1.0 Address rejected. | DSN generated by: | HK2PR04MB3889.apcprd04.prod.outlook.com | Remote server: | stmp-fw-0102.amazon.com
Reported error: | 550 5.0.350 Remote server     returned an error -> 550 #5.1.0 Address rejected.
DSN generated by: | HK2PR04MB3889.apcprd04.prod.outlook.com
Remote server: | stmp-fw-0102.amazon.com

**Comment by JohnHe404** [comment]
How do I get sdk v2 private and public keys?

**Comment by bjguillot** [comment]
amazon-pay-delivery-notifications@amazon.com

Oops, looks like we had a bad address, I'll go fix that now.  There needs to be an "s" on the end.

You need to generate the public and private key on your side (see the openssl steps on the main README page) and then send us your public key.  Never send private keys.

Be sure you send along your Merchant ID, public key, and tell us the relevant merchant region (US, EU, UK, JP).

Do not reply with this information here, please send to the email address above.

**Comment by JohnHe404** [comment]
Thank you!
