### ISSUE TITLE
ToJson serializes payload including type names

### ISSUE THREAD

**Issue by mgesing** [amzn/amazon-pay-api-sdk-dotnet#11]
The SDK serializes the CreateCheckoutSessionRequest to something like
`{"$type":"Amazon.Pay.API.WebStore.CheckoutSession.CreateCheckoutSessionRequest, Amazon.Pay.API.SDK","storeId":"amzn1.application-oa2-client.xxxxx".....
`

Which leads to an API error:
Session ID: 261-4620331-2863352
Error Code: UnrecognizedField 
Error Message: The field '$type' is invalid for this API.

Probably `TypeNameHandling = TypeNameHandling.None` has to be added [here](https://github.com/amzn/amazon-pay-api-sdk-dotnet/blob/master/Amazon.Pay.API.SDK/Types/ApiRequestBody.cs#L19).

I am using Newtonsoft.Json version 13.0.1.

**Comment by shangamesh** [comment]
Thanks for the bringing up issue.
We are working on multiple requests & will plan to handle this case as well. We have a plan to release new version in Jan 2022

**Comment by mgesing** [comment]
The reason for this problem is that we globally set TypeNameHandling.Objects via Newtonsoft.Json.JsonConvert.DefaultSettings at application startup. So this is more of a minor issue.

**Comment by mgesing** [comment]
Resolved, thank you.
