### ISSUE TITLE
An exception is occured when calling the UpdateChargePermission API

### ISSUE THREAD

**Issue by xin9le** [amzn/amazon-pay-api-sdk-dotnet#5]
# Reproduction steps
1.  Make a WebStore payment using Amazon Pay (v1).
1.  Use `WebStoreClient.UpdateChargePermission` API in the Amazon Pay (v2).

# Actual behavior
The SDK fails to parse the response, because of `TransactionAmountExceeded` isn't defined.

```
Error converting value "TransactionAmountExceeded" to type 'Amazon.Pay.API.Types.ReasonCode'.
Path 'statusDetails.reasons[0].reasonCode', line 1, position 867.
```

# Expected behavior
The response should be able to be parsed with no exceptions.

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.

This is because we're missing the "TransactionAmountExceeded" enum in https://github.com/amzn/amazon-pay-api-sdk-dotnet/blob/master/Amazon.Pay.API.SDK/Types/ReasonCodes.cs#L12

We'll work  to get a fix tested and released next week.

**Comment by bjguillot** [comment]
@xin9le, I apologize for the delay.  We have published a fix for this: https://github.com/amzn/amazon-pay-api-sdk-dotnet/releases/tag/2.3.1

It also also available in Nuget as well: https://www.nuget.org/packages/Amazon.Pay.API.SDK/2.3.1

Please try this and let us know if it resolves your issue.

**Comment by xin9le** [comment]
Thanks for the fix! It worked as expected👍

**Comment by xin9le** [comment]
@bjguillot 
I found a typo. Please check if it is correct.
https://github.com/amzn/amazon-pay-api-sdk-dotnet/commit/0162784d3ca6e8de0d6173937fc3fef1c04d0104#r42453593

**Comment by xin9le** [comment]
@bjguillot 
I added pull-request #6. Please check it out.

**Comment by bjguillot** [comment]
We have accepted your pull request.  It's merged now.  We'll be tagging it as version 2.3.2 in just a moment and then adding it to the Nuget repo.
