### ISSUE TITLE
Recurring payments (subscriptions)

### ISSUE THREAD

**Issue by verelpode** [amzn/amazon-pay-api-sdk-dotnet#9]
Congrats on the progress with API/Checkout V2!  I can see that the team has made some great improvements over the previous SDK.  While looking through API/Checkout V2, I find myself thinking "Nice", and "Oh yeah that's nice", and "Nice again".   In contrast, with the previous SDK + Web API + integration guides... well... they're also good but unfortunately there were multiple "What the?!" moments.  Happily those issues are improved in the new V2.

However, although I'm burning to use the great improvements in V2, sadly I can't use it at all because V2 does not yet support recurring payments/subscriptions, right?

Is there any rough estimate on when V2 will support recurring payments?   I'd love to start using V2.

**Comment by lemked** [comment]
Dear @verelpode ,

Thank you for your feedback on the SDK, much appreciated.

I'm happy to inform you that recurring is already supported by our product, see the [release note here](https://amazonpaycheckoutintegrationguide.s3.amazonaws.com/amazon-pay-checkout/release-notes.html#july-13-2020). The SDK contains all required types like the [Recurring ChargePermissionType](https://github.com/amzn/amazon-pay-api-sdk-dotnet/blob/master/Amazon.Pay.API.SDK/WebStore/Types/ChargePermissionType.cs#L13) and [RecurringMetadata](https://github.com/amzn/amazon-pay-api-sdk-dotnet/blob/master/Amazon.Pay.API.SDK/WebStore/Types/RecurringMetadata.cs). Your feedback is a great hint that we're currently missing some code samples though in the SDK's README - will follow-up on that.

Kind regards,
Daniel

**Comment by lemked** [comment]
Code sample has been added to the README: https://github.com/amzn/amazon-pay-api-sdk-dotnet#amazon-pay-button-recurring-payment

Closing issue. Please re-open in case that further assistance is required on the topic.
